development:
  adapter: postgresql
  encoding: unicode
  database: my_aws_app
  # pool: 5
  host: localhost
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: my_aws_app
  username: postgres
  password: postgres
  host: localhost
  port: 5432
 # <<: *default
 #  adapter: postgresql
 #  encoding: unicode
 #  database: my_aws_app
 #  host: localhost
 #  pool: 5
 #  username: postgres
 #  password: postgres