development:
  adapter: postgresql
  encoding: unicode
  database: my_aws_app
  # pool: 5
  host: localhost
  username: postgres
  password: postgres

# production:
#  <<: *default
#  database: my_aws_app
#  username: postgres
#  password: i@_ms_!  