development:
  adapter: postgresql
  encoding: unicode
  database: my_aws_app
  # pool: 5
  host: localhost
  username: postgres
  password: postgres

production:
 <<: *default
  adapter: postgresql
  encoding: unicode
  database: my_aws_app
  host: localhost
  username: postgres
  password: postgres